
drop table if exists detalle_pedido CASCADE


drop table if exists estado_pedido CASCADE


drop table if exists obra CASCADE


drop table if exists pedido CASCADE


drop table if exists producto CASCADE


create table detalle_pedido (
                                id integer generated by default as identity,
                                cantidad integer,
                                precio double,
                                producto_id integer,
                                detalle_pedido_id integer,
                                primary key (id)
)


create table estado_pedido (
                               id integer generated by default as identity,
                               estado varchar(255),
                               primary key (id)
)


create table obra (
                      id integer generated by default as identity,
                      descripcion varchar(255),
                      primary key (id)
)


create table pedido (
                        id integer generated by default as identity,
                        fecha_pedido TIMESTAMP,
                        estado_pedido_id integer,
                        obra_id integer,
                        primary key (id)
)


create table producto (
                          id integer generated by default as identity,
                          descripcion varchar(255),
                          precio double,
                          primary key (id)
)


alter table detalle_pedido
    add constraint FK2yc3nts8mdyqf6dw6ndosk67a
        foreign key (producto_id)
            references producto


alter table detalle_pedido
    add constraint FKe5gh1dmw2643f1krshho8ngg0
        foreign key (detalle_pedido_id)
            references pedido


alter table pedido
    add constraint FKpapbin6tgk2j5es15ajwxfmv2
        foreign key (estado_pedido_id)
            references estado_pedido


alter table pedido
    add constraint FK2e5r5gjfylukkumn894amwcgs
        foreign key (obra_id)
            references obra